### ISSUE TITLE
How can I enable udp support ?

### ISSUE THREAD

**Issue by meson10** [justindowning/puppet-influxdb#12]
Am I missing a trick here ?

It would require a subsection like this, but I cannot see a way of providing this in the class initialisation.

``` cfg
[input_plugins]
  # Configure the udp api
  [input_plugins.udp]
  enabled = true
  port = <port>
  database = <database_name>
```

**Comment by justindowning** [comment]
I believe this can be handled now with the `0.9` branch. I will merge this to master and release a new version to the Forge after some feedback. Let me know what you think! #18

**Comment by jdowning** [comment]
This project is no longer maintained. I recommend you check out [golja/influxdb](https://forge.puppet.com/golja/influxdb) for an updated Puppet module for InfluxDB.
