### ISSUE TITLE
Enable configuration of input plugins

### ISSUE THREAD

**Issue by noroute** [justindowning/puppet-influxdb#14]
There is currently no way to enable input plugins (cp. #12).

@justindowning Do you already have an idea on how that should be implemented? I'd be happy to work on that and submit a PR.

The major problem I see is how to cleanly allow users of the puppet module choose which plugins to enable and pass parameters for the different plugins. Modeling everything as a param would hugely increase the param space.

My intuitive solution sketch:
- have a generic 'define' that represents one plugin entry with attributes

Usage would look like this:

``` puppet
include influxdb
influxdb::input_plugin {'collectd':
   database => 'db1',
}
```

Note that as a consequence input plugins would not be disabled by just deleting the instantiation of the define. You'd need to explicitly instantiate it with something like 'ensure => absent'. Do you thinks this should be automatic?

What do you think of the overall approach?

**Comment by justindowning** [comment]
I believe this can be handled now with the `0.9` branch. I will merge this to master and release a new version to the Forge after some feedback. Let me know what you think! #18

**Comment by jdowning** [comment]
This project is no longer maintained. I recommend you check out [golja/influxdb](https://forge.puppet.com/golja/influxdb) for an updated Puppet module for InfluxDB.
