### ISSUE TITLE
[Feature] Manage Databases, database users and cluster admins

### ISSUE THREAD

**Issue by noroute** [justindowning/puppet-influxdb#19]
To have fully managed influxdbs database, user and admin creation also has to be automated. There is an implementation in https://github.com/blom/puppet-influxdb that's using the influxdb ruby client gem.

We're currently using that in our puppet module that uses your influxdb-puppet module to set up influxdb instances. Would you be interested in integrating that into puppet-influxdb or is it out of scope?

I'd be able to supply a PR in a few days if needed. (One issue is that it introduces a dependency on the influxdb ruby gem to your module which is clumsy to install due to a puppet issue that will not be fixed before Puppet 4.0  (see https://tickets.puppetlabs.com/browse/PUP-1073)).

**Comment by jdowning** [comment]
This project is no longer maintained. I recommend you check out [golja/influxdb](https://forge.puppet.com/golja/influxdb) for an updated Puppet module for InfluxDB.
